#!/bin/bash

MAX_ARGS=9
echo "// !!!                      IMPORTANT NOTE                          !!!"
echo "// !!! This header file is dynamically generated by gen_va_macro.sh !!!"
echo "// !!! Please do NOT keep your modifications here.                  !!!"
for (( i = 1; i <= $MAX_ARGS; i++ )); do
    echo -n "#define VA_GET_$i("
    for (( j = 1; j <= i; j++ )); do
        echo -n "_$j, "
    done 
    echo "...) _$i"
done
echo ""

echo "// This section is used for debugging only, when printing type of args"
echo "// is required."
for (( i = 1; i <= $MAX_ARGS; i++ )); do
    echo -n "#define VA_GET_S$i("
    for (( j = 1; j <= i; j++ )); do
        echo -n "_$j, "
    done 
    echo "...) #_$i"
done
echo ""

echo "// This section is used for getting logging function"
for (( i = 1; i <= $MAX_ARGS; i++ )); do
    echo -n "#define VA_GET_LOG$i("
    for (( j = 1; j <= i; j++ )); do
        echo -n "_$j, "
    done 
    echo "...) log_##_$i"
done
echo ""


echo "#define VA_MAP_UNROLL_1(arg, ...)                         \\"
echo "    arg[0].selfprint = VA_GET_LOG1(__VA_ARGS__);          \\"
echo "    arg[0].addr = &op1;                                   \\"
echo "    arg[0].type = VA_GET_S1(__VA_ARGS__);"
echo ""
for (( i = 2; i <= $MAX_ARGS; i++ )); do
    j=$((i-1));
    echo  "#define VA_MAP_UNROLL_$i(arg, ...)                        \\"
    echo  "    VA_MAP_UNROLL_$j(arg,  __VA_ARGS__)                   \\"
    echo  "    arg[$j].selfprint = VA_GET_LOG$i(__VA_ARGS__);        \\"
    echo  "    arg[$j].addr = &op$i;                                 \\"
    echo  "    arg[$j].type = VA_GET_S$i(__VA_ARGS__);"
    echo ""
done


echo "#define VA_CONCAT_DECL_1(...) VA_GET_1(__VA_ARGS__) op1"
for (( i = 2; i <= $MAX_ARGS; i++ )); do
    j=$((i-1))
    echo "#define VA_CONCAT_DECL_$i(...) VA_CONCAT_DECL_$j(__VA_ARGS__), VA_GET_$i(__VA_ARGS__) op$i"
done
echo ""

echo "#define VA_CONCAT_1() op1"
for (( i = 2; i <= $MAX_ARGS; i++ )); do
    j=$((i-1))
    echo "#define VA_CONCAT_$i() VA_CONCAT_$j(), op$i"
done



